--- 
language: r
warnings_are_errors: false




r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx



before_install:
  - tlmgr install index
  - tlmgr install framed

cache:
  packages: true


jobs:
  allow_failures:
    - os: osx
    - r: oldrel
