--- 
language: r
warnings_are_errors: false




r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

addons:
  apt:
    packages: cowsay
  brew:
    packages:
      - index
      - framed

cache:
  packages: true


jobs:
  allow_failures:
    - os: osx
    - r: oldrel
