--- 
language: r
warnings_are_errors: false




r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx      # Problems with latex
  #- windows  # Not supported

addons:
  brew:
    packages:
      - basictex

before_install:
  - sudo tlmgr install index framed || echo "failed install"

cache:
  packages: true


jobs:
  allow_failures:
    - os: osx
    - r: oldrel
