--- 
language: r
warnings_are_errors: false




r:
  #- oldrel
  - release
  - devel

os:
  - linux
  #- osx
  - windows

addons:
  apt:
    packages: cowsay
  brew:
    packages:
      - basictex

before_install:
  - sudo tlmgr install index framed || echo "failed install"

cache:
  packages: true


jobs:
  allow_failures:
    - os: osx
    - r: oldrel
